/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_mmi_AccelerationEvent */

#ifndef _Included_br_ufscar_lince_mmi_AccelerationEvent
#define _Included_br_ufscar_lince_mmi_AccelerationEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_mmi_AccelerationEvent
 * Method:    getXValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_mmi_AccelerationEvent_getXValue
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_mmi_AccelerationEvent
 * Method:    getYValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_mmi_AccelerationEvent_getYValue
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_mmi_AccelerationEvent
 * Method:    getZValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufscar_lince_mmi_AccelerationEvent_getZValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
