/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_mmi_IDeviceComm */

#ifndef _Included_br_ufscar_lince_mmi_IDeviceComm
#define _Included_br_ufscar_lince_mmi_IDeviceComm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_mmi_IDeviceComm
 * Method:    create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_br_ufscar_lince_mmi_IDeviceComm_create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufscar_lince_mmi_IDeviceComm
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_IDeviceComm_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
