/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_mmi_JavaEvent */

#ifndef _Included_br_ufscar_lince_mmi_JavaEvent
#define _Included_br_ufscar_lince_mmi_JavaEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_mmi_JavaEvent
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_br_ufscar_lince_mmi_JavaEvent_create
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
