/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_mmi_MMIManager */

#ifndef _Included_br_ufscar_lince_mmi_MMIManager
#define _Included_br_ufscar_lince_mmi_MMIManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIManager_release
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    connectWiiMote
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIManager_connectWiiMote
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    postEvent
 * Signature: (Lbr/ufscar/lince/mmi/MMIEvent;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIManager_postEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    postXMLEvent
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIManager_postXMLEvent
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    registerDevice
 * Signature: (Lbr/ufscar/lince/mmi/IDeviceComm;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIManager_registerDevice
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    unregisterDevice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIManager_unregisterDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    removeEventListener
 * Signature: (Lbr/ufscar/lince/mmi/MMIEventListener;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIManager_removeEventListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    waitForUnlockCondition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIManager_waitForUnlockCondition
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_br_ufscar_lince_mmi_MMIManager_create
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIManager_destroy
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    doAddEventListener
 * Signature: (Lbr/ufscar/lince/mmi/MMIEventListener;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIManager_doAddEventListener
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    doCallDeviceService
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIManager_doCallDeviceService
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     br_ufscar_lince_mmi_MMIManager
 * Method:    doGetDevicesName
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_br_ufscar_lince_mmi_MMIManager_doGetDevicesName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
