/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_mmi_MMIEventListener */

#ifndef _Included_br_ufscar_lince_mmi_MMIEventListener
#define _Included_br_ufscar_lince_mmi_MMIEventListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_mmi_MMIEventListener
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_br_ufscar_lince_mmi_MMIEventListener_create
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_mmi_MMIEventListener
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIEventListener_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
