/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_mmi_KeyEvent */

#ifndef _Included_br_ufscar_lince_mmi_KeyEvent
#define _Included_br_ufscar_lince_mmi_KeyEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_mmi_KeyEvent
 * Method:    getKeyId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufscar_lince_mmi_KeyEvent_getKeyId
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
