/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufscar_lince_mmi_MMIEvent */

#ifndef _Included_br_ufscar_lince_mmi_MMIEvent
#define _Included_br_ufscar_lince_mmi_MMIEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufscar_lince_mmi_MMIEvent
 * Method:    getDeviceId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufscar_lince_mmi_MMIEvent_getDeviceId
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_mmi_MMIEvent
 * Method:    getEventType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufscar_lince_mmi_MMIEvent_getEventType
  (JNIEnv *, jobject);

/*
 * Class:     br_ufscar_lince_mmi_MMIEvent
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufscar_lince_mmi_MMIEvent_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
